package au.com.ip.api.customerprofiles.service;

import au.com.ip.api.customerprofiles.dto.Profile;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * ProfileServiceImpl class acts as implementation of Profile Service. Basic management operations are provided.
 * In next version this service will be talking to JPA Repository
 */
@Service
public class ProfileServiceImpl implements ProfileService {
    // A simple in-memory map simulating profiles storage
    private static Map<String, Profile> profileMap = new HashMap<>();

    /**
     * Retrieve Profile by profile id
     * @param id Profile Id
     * @return Profile
     */
    @Override
    public Profile getProfileById(String id) {
        return profileMap.get(id);
    }

    /**
     * Save new customer profile
     * @param profile New Profile
     * @return Saved Profile
     */
    @Override
    public Profile saveProfile(Profile profile) {
        // Simulating Autogenerated Primary Key
        UUID uuid = UUID.randomUUID();

        profile.setProfileId(uuid.toString());
        profileMap.put(uuid.toString(), profile);
        return profile;
    }

    /**
     * Update Profile
     * @param id Profile Id
     * @param updatedProfile Changed Profile object
     */
    @Override
    public void updateProfile(String id, Profile updatedProfile) {
        profileMap.put(id,updatedProfile);
    }

    /**
     * Delete Customer Profile by Id
     * @param id provided profile id
     */
    @Override
    public void deleteProfile(String id) {
        profileMap.remove(id);
    }
}
